from onetimepass import valid_totp
from secrets import choice


def generate_secret():
    key = ''
    while len(key) < 16:
        key += choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ234567')
    return key


key = generate_secret()
print('Enter the following key in your authenticator app: ', key)
print("""
Instructions for saving this secret on Google Authenticator:
1. Open Google Authenticator.
2. Click plus icon at the right bottom.
3. Click Enter a setup key.
4. Enter an Account name of your choice and enter the secret provided above.
5. Click Add.
""")
while True:
    otp = int(input('Please enter the otp generated by your authenticator app: '))
    authenticated = valid_totp(otp, key)
    if authenticated:
        print('Correct otp, Authenticated!')
    elif not authenticated:
        print('Wrong otp, please try again.')